_credits = "Game^1 Author^2: &/cYDobby233Liu/cW^5&"
_credits += "Simplified^1 Chinese^1 Translation^2: &/cYDobby233Liu/cW^5&"
_credits += "English^1 Translation^2: &/cYDobby233Liu/cW^5&"
_credits += scr_shuffletext("VAPOR^1WAVE") + " (Pseduo)^2 Translation^2: &/cYDobby233Liu/cW^5&"
_credits += "Data^1min^1ing^2: &/cYE^2 V^2 E^2 R^2 Y^2 O^2 N^2 E/cW^5&"
_credits += "Undertale^2 &^2 Deltarune^2: &/cYToby^2 Fox/cW^5&"
_credits += "/cYIf these people was not there^2,& this game won't be possible.^2/cW&"
_credits += "/cRG^3	o^3	o^3	d^3	n^3	i^3	g^3	h^3	t/cW^1!E"
_credits += "&^9^9^9(well^2, If^1 you^3 see this text^2, you must^3 edited the game^2 or^1 data^1mining^2 the^1 game^2)"
return _credits